package com.martkplaats.backend.model;

public enum Category {
    AUDIO,
    AUTOS,
    BABIES,
    BANDENPLAKSETJES,
    BOEKEN,
    CHALETS,
    DATING,
    EETTAFELS,
    FIETSEN,
    GAMES,
    HORLOGES,
    IPHONY,
    JACUZZI,
    KNIKKERS,
    LUCHTBALLONNEN,
    MOTOREN,
    MUZIEKINSTRUMENTEN,
    NACHTKASTJES,
    OPENHAARDHOUT,
    PCS,
    POKEMONKAARTEN,
    QUADS,
    RACEFIETSEN,
    SIERRADEN,
    SPORT,
    TELEFOONS,
    TICKETS,
    UKELELE,
    VACATURES,
    VAKANTIE,
    WCS,
    XBOX,
    YOGHURT,
    ZONNESCHERMEN
}
